### PR TITLE
Add ‘scrollEventDelay’ option for adjusting scroll event throttle.

### PR DESCRIPTION
**Pull request by matthewmcvickar**
This fixes issue #57.

This also fixes a missing development dependency and two typos in the README.

I have tried to follow the contributions guidelines but please let me know if there's anything I can do to improve my contribution.

Thank you!

### CODE REVIEW

**Comment by cferdinandi** [comment]
Hi @matthewmcvickar, this looks really good, thanks! My only feedback: based on what you did here, I don't think the variable here is necessary:

```js
var settings, eventTimeout, docHeight, header, headerHeight, currentNav, scrollEventDelay;
```

`scrollEventDelay` is already set as part of the `settings` object, right?

**Comment by cferdinandi** [comment]
PS: Thanks for fixing that typo!

**Comment by matthewmcvickar** [comment]
@cferdinandi Yes, you're right; I've removed it. Thank you very much!

**Comment by cferdinandi** [comment]
Thanks! I'm happy to merge this, BUT... I wanted to float something by you first.

Given the use case around this, would it make it more sense to have an option to "wait until scrolling has stopped" before highlighting? 

Right now, the delay is kind of arbitrary and you've got to guesstimate based on how big your navigation/page is (and also, how fast someone scrolls, right?).

The default delay was chosen for optimal frame rate smoothness. Your use case here is totally valid, and this is absolutely the easiest way to address it, but I'm not sure it's the best.

What do you think?

**Comment by cferdinandi** [comment]
BTW, the method here: we'd leave our default delay time unchanged, and add a "wait until scrolling is stopped" option in the settings as a `true`/`false` boolean. 

We'd switch a few things up in the `eventHandler` with some `if`/`else` logic to change when things run. We might need a new variable, something like `isScrolling`. I'm happy to help implement this.

**Comment by cferdinandi** [comment]
Forked into https://github.com/cferdinandi/gumshoe/pull/59

**Pull request closed without merging**
