### PR TITLE
Invoke callback when getCurrentNav() finds no active nav

### PR DESCRIPTION
**Pull request by ezzatron**
When using a callback, gumshoe does not currently invoke the callback in cases where `getCurrentNav()` finds no active nav. This can happen when the user scrolls above the first nav.

In my use case, I implement my own addition and removal of `active` classes to the menu via the callback. If the callback is not invoked when there is no active nav, I cannot remove the `active` classes from the menu as appropriate. Furthermore, there is no way to extract the "current nav" data from gumshoe, so I can't even write an effective workaround.

This PR addresses the issue in two ways:

- When `getCurrentNav()` is invoked, if there is no "active" nav, the callback will be invoked with `undefined` as the nav.
- The active nav data is now returned from `getCurrentNav()`, allowing for better handling of future edge-cases.

### CODE REVIEW

**Comment by cferdinandi** [comment]
Thanks for this (and also for documenting this so thoroughly).

From a quick look at this, my only concern: will this result in the callback being invoked twice in certain circumstances?

**Comment by ezzatron** [comment]
There are only 2 places that I can see where the callback is invoked; in `activateNav()` and now in `getCurrentNav()`. Since whenever `getCurrentNav()` calls `activateNav()`, it returns immediately, I can't see any obvious case where the callback would be invoked twice.

**Comment by ezzatron** [comment]
Also, there's a demo of this code running on http://eloquent-software.com/phony/ right now, if you'd like to see it in action.

**Comment by cferdinandi** [comment]
hi @ezzatron - sorry, finally got around to looking at this again. I totally see what's happening now. This looks great! Merged!

**Comment by cferdinandi** [comment]
Also, THANK YOU for one of the best PRs I've ever gotten. Well done!

**Comment by ezzatron** [comment]
No worries, thanks for a great library!

**Pull request merged**
