### PR TITLE
Fix issue where top-most nav remains active even when scrolling well …

### PR DESCRIPTION
**Pull request by altano**
…above it

### CODE REVIEW

**Comment by cferdinandi** [comment]
I'm not familiar with this issue. Can you please provide a reduced test case so I can understand what this PR is addressing?

**Comment by altano** [comment]
It was actually pretty hard to get the gumshoe dev environment setup and my machine, presumably since I'm using Windows, so I don't have a test case, but I can share a JSFiddle with you that reproduces the problem: http://jsfiddle.net/altano/4pq0y304/17/embedded/result/

1. Notice nothing in the nav is highlighted
1. Scroll down until any of the nav items are selected
1. Scroll back up to the top of the page. Notice that the first nav item is still highlighted even though it's way below the fold/bottom of the viewport at this point.  gumshoe has no logic for going ABOVE all the headers.

You can also cause another issue that's worse:

1. Scroll down far
1. Press home key on keyboard

A randomly selected nav will get highlighted since the scroll event is fired non-deterministically as your browser scrolls to the top.

**Comment by cferdinandi** [comment]
@altano Perfect, that's just what I needed, thanks! I'll give this a quick code review today, but I like this. Thanks for the PR and the test case.

**Comment by cferdinandi** [comment]
I made a few small tweaks:

1. I updated the version number.
2. I added an `isInViewport` check before activating the last element when at the bottom of the page (in keeping with the spirit of what you're trying to do here).

https://github.com/cferdinandi/gumshoe/pull/40

**Pull request merged**
